spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/moyeolak?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: moyeolak
      password: moyeolak
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:postgresql://localhost:5432/moyeolak_spatial
      username: moyeolak
      password: moyeolak
      driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    primary:
      ddl-auto: create

  sql:
    init:
      mode: always

kakao:
  api:
    key: ${KAKAO_API_KEY}

odsay:
  api:
    key: ${ODSAY_API_KEY}

google:
  api:
    key: ${GOOGLE_API_KEY}
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, caches, prometheus
  endpoint:
    caches:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cache: trace   # 캐시 히트/미스 로그
