server:
  port: 8080
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:native}

spring:
  datasource:
    primary:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:postgresql://${POSTGIS_HOST}:${POSTGIS_PORT}/${POSTGIS_DB_NAME}
      username: ${POSTGIS_USERNAME}
      password: ${POSTGIS_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    primary:
      ddl-auto: none

kakao:
  api:
    key: ${KAKAO_API_KEY}

odsay:
  api:
    key: ${ODSAY_API_KEY}

google:
  api:
    key: ${GOOGLE_API_KEY}

logging:
  level:
    root: warn
    com.dnd.moyeolak: info
